### Register a new user
POST {{host}}/auth/register
Content-Type: application/json
Accept: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "secret123",
    "password_confirmation": "secret123"
}

### Login user and retrieve token
POST {{host}}/auth/login
Content-Type: application/json
Accept: application/json

{
    "email": "john.doe@example.com",
    "password": "secret123"
}

> {% client.global.set("access_token", response.body.token); %}

### Get authenticated user info
GET {{host}}/auth/me
Accept: application/json
Authorization: Bearer {{access_token}}

### Refresh JWT token
POST {{host}}/auth/refresh
Accept: application/json
Authorization: Bearer {{access_token}}

### Logout user
POST {{host}}/auth/logout
Accept: application/json
Authorization: Bearer {{access_token}}
